language: java
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: script
  script: mvn deploy -X -s .travis.settings.xml
  skip_cleanup: true
env:
  global:
  - secure: ZXcjSkQfeVcOPc/pYjITx/xpuSlTrbWtaOOphJKbF1Tp7Yy9qrVjpjVom/N89Zzqio77c7XtqnqTyftQ945jp4olR2W2GgU27dE/Hn2gwTepW8zm9R9JvHekxxkQH3kySQWJdMNG5gKq7Q1YiJfEnpa6a9TsWhALdmvdseELwSDGrktapVaJwnkbCNDjUh6KYk3bOby+Bs58c2qwQlfjsdbnieiA0O5HiF/svoPCrENpGJIEDbR8+BbEMN6b5nln64nAO03TrdhS7piGsaB5pavtcRz7UHUgfbTLAzLp/cZgNkd18wV4QCiWtUtGYbN8uKd4tdFkvqAx7FINNtkXPfyzmhHLwvVphRXenaDRQDWDZ1zDKbfeLurYXPBOnE7e9qHQW78wBdggxSo7EsHaq+/DD2M1QOmfBnjDwvap58PN5qbZ4vggxQwCr4lGwDvOBlSiX7GEWizJTHmk62SBa8qAzduzWjblMvBZoNfm9aufl2RXWaOVoBAbbjgCXnbLQAZkeUzUW23j4goKkPDYLcJC/i0t4Ax7ZSFj1HplRowSzZmbUShi73vDQ4doNnmb0k9MmOm59DJaCiPCqOKMOG5L9kWGynbHLnO8Xcnk/BwnVUoFaVGRWo5d7s0dzhm4xg5kTtUaNmfYW7oxcDXETRNAuMHltJImbN7KZ7Hl+ZE=
  - secure: JxIKK5HkaxJX994CuztmTykNcpalg4wXpW66C+jkRzZZFMKcbcEKnGJAWK6UHTMmqokigToqnAwrli14OldRr5kb8mNZhs8cL4LBywE0SYVTsi15lOjTjGxXkJVuiW5jzZNq5qT+aBBxx1hLRDBPujTIyTZlJMCrUpG/+fBGsKyAP+25545nE8Cq48YMpwBf/5Y/fD5fzxTtZkcxGODnRnUXhnluvzKTLZNNcpQiiYaYiD39IJyl9tiKn/ZiSZOskr/pccnnRH1GFVG2wsIYTbW3JPnc3cFYCaQi8+vHHmx3cVGW/MzLw9WvOSH3ByXq0Zgv7485aPBnrUAbzFDkuFJpu8vuNgNr8c6KblYfeOPqT4AUgiYMXx+5Mym84UaSN9PB1kQAiC0nV4Il5qBWfHu620EU8w3hGVd/RYgpANuOGv8J7ukXJiV1KFfvUKKk6jQjws6y4o+9xkSOCpmS7Zb/1w+CxPsBQHjRg6zjkNIgNRqqb2fsyQFoRBgYEUzbJ8595RdnoRIKJknzj1OsmX8npIRoySZip7+tZJGR3MA0BE9NXK0tf/pzTRGCqpIzvuqoN5MluS9b77WzC9FYqf+3c6WQuE4RAwWCfoJ27bZDgZ/DfaRXX2NzWKBSquURC5CgCJxC1APHUlM81TExONNsPEg7piW5FXVp0PNy3qA=
