language: java
install: true
deploy:
  - provider: script
    script: mvn deploy -Ppublic -s .travis.settings.xml
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: mvn deploy -Ppublic -s .travis.settings.xml
    on:
      branch: develop
env:
  global:
  - secure: YfzsJAIUALNUW2/zv3NKWpA+7DzK9JnTtCnHrUmBGJGAwJmCaOiO4dPSp6R0/SoxQGD5dIv7vE5i/8RdHqm/py2ViRLxJFjgVN9mu4YOPnnUVbSD2DOJg/q8NpJDobZgHM67g3SmIDmOtuqKCLItRrKZ5OBOAt9nS2+0QLS1oF//7jmIqDcPzm97UWXMvnhi5vMfym+g3F2RbiIVPk5V+eyCRppSuXsazJiW1YLLNRNNW6eYkokj7RnMWoV3Gbn4LiAWETHXcb8g4IF4wvcMcokAqxKXhlwy4/kbmp/vKz97+8tqXK105SEFTTSgvxnWs2/OOHUVmZujVBWpqLX3LuSgFhSn1mQtMYUHEsQfhVMohuqxo0VpnaMp/N+/vdiO8FdEElYue0Eb6Q9/7MqE7jB/uSF4A3cXaJgPiAblKRx+Ei6FT7tncYFW4YWT2eoJKyIrkb5Bshr3ZVkyww4qz4hp/oiXwRxwDJ+hF4czJqLmPtWttJihcfyYVT+ycPtoph83a2eJS2aZlSdJm5QjdizIc8Xhdg/WgDCt6elA/r/AMn3yJbtDhey5/f+I+GfTSLuSvBDaEOg0+Qag1HNZQUVZbypiVTBTgPQz8BCXGH1pfj6cSYzefC4QNPgGptN8q0eivmsVwq0MjQ5yVq38uw35hM8KGQVlBcXsiYih9XA=
  - secure: I66/p6i5sN0mH8y6Dp1aQDtUCvf8/YUalFitxqRusq1wVDoXlmbTePlph0GWIL1xNHapljuVTHFlWnBr6RgsqPfj0Fe5te9snEKo8rftWS3aSkSdkF/LU/nWchH+1qxkr8D50wL4qZ4sh5mpOxRASyoNwaIAfEt2ajBqebW1hYFohGhMeONe3ypFgL5NLtBCInGMRMEVjrXhbbLVbqJvOh+kXlM9JbITo6lss43/pEAX6p39a3lwMurtDv6kVmVKfsUJGPO/WQCdVrK0SX7aOyBfseTibi4wEpOlyDCvdOqRHYSB3rVzdLriRxDF2SEoSgUs+X3vU6ChuqNMtnmVjTQ+TC+aypmWkYQdBQrp/h+z99T68v/ATlKrUgSf80ILPKTBhSZOHu5BxJbmC2iPynRhu+mEN4gFNeZ+m5Dv8KUaTVDUQjig8eam57QM3dOnjT8sP0cXJ8PJ0E2SbJvH9MO1Bue7CcIi2rtCZ2Je95RHpxZgAJfkUtXC/4pm5bbLTUejiqjfDa/n+WRCONRpSaQsALb5lotuSFDNpTOtOMtZMH3lNEnFDRgxJzz+725CMRONYSTDSX/Mp3HhhxYFvAMLtUbbCOHI7d2DBiWRNljc801tLZJiLc6dZQ7w4JFr0fKeQgoyBN9wnnyZ1QMinuEAIpa7QNA7yKcZjrbFV+M=
