### Develop Pipeline
### Develop Snapshot Branch X.X.X-SNAPSHOT
### Project :: KMDP API4KP

# !! Downstream Build: kmdp-bom; develop !!

trigger: 
    - develop

pool:
  vmImage: 'ubuntu-latest'

# ------------------ PIPELINE STEPS  ------------------
steps:
- script: |
    echo Starting KMDP Develop Branch!
    echo Project :: KMDP API4KP
  displayName: 'Pipeline Steps Started'

# Set JDK 11 and MVN Validate Project
- task: Maven@3
  displayName: 'Set Maven JDK 11'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'validate'
    options: '-ntp'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'

# Read Root POM File and Set GAV Variables
- task: PowerShell@2
  displayName: 'Read POM/Set GAV Variables'
  inputs:
    targetType: 'inline'
    script: |
      [xml]$pomXml = Get-Content .\pom.xml
      Write-Host ---- Group Id, Artifact Id, Version ----
      Write-Host GroupId: $pomXml.project.groupId
      Write-Host ArtifactId: $pomXml.project.artifactId
      Write-Host Version: $pomXml.project.version
      # Write GAV to local task variables
      $groupId=$pomXml.project.groupId
      $artifactId=$pomXml.project.artifactId
      $version=$pomXml.project.version
      # Set GAV to pipeline variables
      Write-Host "##vso[task.setvariable variable=projectSnapShotVersion]$version"
      Write-Host "##vso[task.setvariable variable=projectGroupId]$groupId"
      Write-Host "##vso[task.setvariable variable=projectArtifactId]$artifactId"

# Write GAV variables for validation
- task: PowerShell@2
  displayName: 'Validate Env Variables'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host --------------------------------
      Write-Host POM Variables:
      Write-Host Project Group ID: $env:GROUP_ID
      Write-Host Project Artifact ID: $env:ARTIFACT_ID
      Write-Host Project Snapshot Version: $env:PROJECT_SNAPSHOT_VERSION
  env: 
    ARTIFACT_ID: $(projectArtifactId)
    PROJECT_SNAPSHOT_VERSION: $(projectSnapShotVersion)
    GROUP_ID: $(projectGroupId)

# SLM Versioning Policy (No Version Change)
- task: AlmVersioning@4
  displayName: 'SLM Update Version/Build #'
  inputs:
    projectType: java
    versionFilePath: pom.xml
    versionTransformation: none

# Download Secure Settings m2 File
- task: DownloadSecureFile@1
  displayName: 'Download Secure m2'
  name: settingsxml
  inputs:
    secureFile: settings-dev.xml

# Write settings file to Build Server
- task: PowerShell@2
  displayName: 'Update m2 Settings File'
  inputs:
    targetType: 'inline'
    script: |
      New-Item -Type Directory -Force "${HOME}/.m2"
      Copy-Item -Force "$(settingsxml.secureFilePath)" "${HOME}/.m2/settings.xml"

# Authenticate to Maven Feed 
- task: MavenAuthenticate@0
  displayName: 'Maven Authenticate'
  inputs:
    artifactsFeeds: 'KMD'

# Maven Deploy to AzDo KMD Artifacts
- task: Maven@3
  displayName: 'Maven Deploy to KMD Artifacts'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'deploy'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    options: '-DaltDeploymentRepository=KMD::default::https://pkgs.dev.azure.com/mclm/_packaging/KMD/maven/v1 -ntp'

# ------------------ END PIPELINE  ------------------
- script: |
    echo Ending Develop Branch Pipeline!
  displayName: 'Pipeline Steps Ended' 
