### Feature Pipeline
### Feature Snapshot Branch X.X.X-SNAPSHOT
### No deployments to artifacts
### Project :: API4KP Features another test again - try again2

# !! No Downstream Builds !!

trigger:
- feature*

pool:
  vmImage: 'ubuntu-latest'

# ------------------ PIPELINE STEPS  ------------------
steps:
- script: |
    echo Starting KMDP Feature Branch Pipeline!
    echo Project :: API4KP
  displayName: 'Pipeline Steps Started'

# Set JDK 11 and MVN Validate Project
- task: Maven@3
  displayName: 'Set Maven JDK 11'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'validate'
    options: '-ntp'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'

# Read Root POM File and Set GAV Variables
- task: PowerShell@2
  displayName: 'Read POM/Set GAV Variables'
  inputs:
    targetType: 'inline'
    script: |
      [xml]$pomXml = Get-Content .\pom.xml
      Write-Host ---- Group Id, Artifact Id, Version ----
      Write-Host GroupId: $pomXml.project.groupId
      Write-Host ArtifactId: $pomXml.project.artifactId
      Write-Host Version: $pomXml.project.version
      # Write GAV to local task variables
      $groupId=$pomXml.project.groupId
      $artifactId=$pomXml.project.artifactId
      $version=$pomXml.project.version
      # Set GAV to pipeline variables
      Write-Host "##vso[task.setvariable variable=projectSnapShotVersion]$version"
      Write-Host "##vso[task.setvariable variable=projectGroupId]$groupId"
      Write-Host "##vso[task.setvariable variable=projectArtifactId]$artifactId"

# Write GAV variables for validation
- task: PowerShell@2
  displayName: 'Validate Env Variables'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host --------------------------------
      Write-Host POM Variables:
      Write-Host Project Group ID: $env:GROUP_ID
      Write-Host Project Artifact ID: $env:ARTIFACT_ID
      Write-Host Project Snapshot Version: $env:PROJECT_SNAPSHOT_VERSION
  env: 
    ARTIFACT_ID: $(projectArtifactId)
    PROJECT_SNAPSHOT_VERSION: $(projectSnapShotVersion)
    GROUP_ID: $(projectGroupId)

# SLM Versioning Policy (No Version Change)
- task: AlmVersioning@4
  displayName: 'SLM Update Version/Build #'
  inputs:
    projectType: java
    versionFilePath: pom.xml
    versionTransformation: none

# Authenticate to Maven Feed 
- task: MavenAuthenticate@0
  displayName: 'Maven Authenticate'
  inputs:
    artifactsFeeds: 'KMD'

# Maven Clean Test
- task: Maven@3
  displayName: 'Maven Clean Test'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    options: '-ntp'

# ------------------ END PIPELINE  ------------------
- script: |
    echo Ending Feature Branch Pipeline!
  displayName: 'Pipeline Steps Ended' 
