title: API4KP
email: dsotty@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  API for Knowledge Platforms - Ontology Documentation
baseurl: "/api4kbs"
twitter_username: dsotty
github_username:  sotty

# Build settings
theme: jekyll-theme-time-machine

repository: sotty/api4kbs

plugins:
  - jekyll-sitemap


collections:
  API4KP:
    output: true
    onto:   true
    index:  1
  DOL:
    output: true
    onto:   true
    index:  2
  Extensions:
    output: true
    onto:   true
    index:  3
  Bridges:
    output: true
    onto:   true
    index:  4
  Other:
    output: true
    onto:   true
    index:  5
  OMG:
    output: true
    onto:   true
    index:  6

