title: API4KP
email: dsotty@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  API for Knowledge Platforms - Ontology Documentation
baseurl: "/api4kbs"
twitter_username: dsotty
github_username:  sotty

# Build settings
theme: jekyll-theme-time-machine

repository: sotty/api4kbs

plugins:
  - jekyll-sitemap


collections:
  Normative:
    output: true
    onto:   true
  Informative:
    output: true
    onto:   true
  DOL:
    output: true
    onto:   true
  Bridges:
    output: true
    onto:   true
  OMG:
    output: true
    onto:   true
